### ISSUE TITLE
지나간거 다시 할 수 없을까요ㅠㅠ

### ISSUE THREAD

**Issue by TheBlackonme** [NewsJelly/semantle-ko#11]
지나간 퀴즈들도 다시 해보고싶어요.........
하루 한 번 너무 적어 꿰에엑

**Comment by SuperLeeK** [comment]
275번째부터 참여했는데 앞에 274개의 문제들 풀고싶다아악!!!

**Comment by mumunuu** [comment]
@TheBlackonme 

curl --location --request GET 'https://semantle-ko.newsjel.ly/guess/293/조명'

`{
    "guess": "조명",
    "rank": "정답!",
    "sim": 1
}`

**Comment by heewonlee-nj** [comment]
안녕하세요.

현재 꼬맨틀은 하루에 한 번만 플레이 할 수 있습니다.

꼬맨틀 웹 페이지에 내용처럼, 저희는 [Wordle](https://www.nytimes.com/games/wordle/index.html)과 같은 게임의 핵심 요소는 "하루에 한 번만, 모두가 동일한 정답"이라고 생각합니다.

따라서 꼬맨틀의 정식 기능으로서 지난 문제를 풀 수 있는 기능을 제공할 계획은 없습니다.

앞으로도 꼬맨틀에 대한 많은 관심 부탁드립니다.
감사합니다.
