### ISSUE TITLE
정답 파일 접근 권한 수정 요청

### ISSUE THREAD

**Issue by eogns282** [NewsJelly/semantle-ko#13]
안녕하세요, 제가 너무 재밌게 하고 있습니다!!

이걸로 친구들이랑 내기를 자주 하는데요, 혹시 정답 파일을 접근 불가능하게 따로 관리해주시기는 힘들까요?

감사합니다!

**Comment by heewonlee-nj** [comment]
#12 와 중복된 이슈입니다. 관련 사항은 해당 이슈를 참고해주세요.

**Comment by eogns282** [comment]
Dooray! Failure Notice



  
  
    
    
  
  
    
        Failure Notice
    
  
  
    
        
        Your message sent to
          
***@***.***) 
          has failed to be delivered.
        
        
          Please refer to the below for details.
        
    
  
  
    
      
        
          
            * Recipient : 
***@***.***) 
          
          
            * Sent time : 
2023-01-26T10:13:31
          
          
            * Subject : 
Re: [NewsJelly/semantle-ko] 정답 파일 접근 권한 수정 요청 (Issue #13)
          
          
            
              
                * Remote host said : 
              
              
                
Your mail was denied from the receiver.
                
              
            
                      
          
        
      
    
  
  
    
        
          This message was sent from a notification-only address that cannot accept incoming email.
          For more information, please contact           ***@***.***
        
    
  
  
    
        © Dooray!.

**Comment by eogns282** [comment]
Dooray! Failure Notice



  
  
    
    
  
  
    
        Failure Notice
    
  
  
    
        
        Your message sent to
          
***@***.***) 
          has failed to be delivered.
        
        
          Please refer to the below for details.
        
    
  
  
    
      
        
          
            * Recipient : 
***@***.***) 
          
          
            * Sent time : 
2023-01-26T10:13:32
          
          
            * Subject : 
Re: [NewsJelly/semantle-ko] 정답 파일 접근 권한 수정 요청 (Issue #13)
          
          
            
              
                * Remote host said : 
              
              
                
Your mail was denied from the receiver.
                
              
            
                      
          
        
      
    
  
  
    
        
          This message was sent from a notification-only address that cannot accept incoming email.
          For more information, please contact           ***@***.***
        
    
  
  
    
        © Dooray!.
