### ISSUE TITLE
단어 변경시간

### ISSUE THREAD

**Issue by truevird** [NewsJelly/semantle-ko#14]
질문과 답변에 따르면 단어 변경은 UTC 0900 또는 KST 0000을 기준으로 바뀐다고 나와있는데 그렇다면 시간대가 다르게 적용되는지 궁금합니다.

-UTC 0900는 KST 1800이고, KST 0000는 UTC 1500으로 시간이 맞지 않아 생긴 의문입니다.

수고가 많으십니다.

**Comment by heewonlee-nj** [comment]
해당 문구를 작성할때 착오가 있었던 것 같습니다.
한국표준시 기준 00:00에 변경되는게 맞습니다.
