### ISSUE TITLE
기능추가 제안

### ISSUE THREAD

**Issue by choooooooooi** [NewsJelly/semantle-ko#16]
안녕하세요, 꼬맨틀 항상 잘 플레이하고 있습니다~
정답 맞히고 난 후, 단어를 입력한 순서대로 정렬하는 기능이 추가된다면
친구들이랑 더 재밌게 기록을 공유할 수 있을 것 같아요~

**Comment by heewonlee-nj** [comment]
안녕하세요.

입력하신 정답 목록에서 번호 상단 헤더의 '#'을 클릭하시면 번호순으로 정렬 가능합니다.

감사합니다.
