### ISSUE TITLE
Docker로 꼬맨틀 서버를 열었는데요, 단어는 어느 서버든 고정인가요?

### ISSUE THREAD

**Issue by bicheondev** [NewsJelly/semantle-ko#6]
아래 설명해 주신 방법 대로 Docker로 웹페이지를 여는 것은 성공했습니다만, 정답이 원래 사이트를 따라가네요.

따로 정답을 지정하거나 원래 사이트와 다르게 할 수는 없나요?

**Comment by ChoWonmin** [comment]
data/secrets.txt 파일에 정답이 하드코딩되어있습니다.

semantle.py의 FIRST_DAY부터 정답이 시작됩니다.

`
FIRST_DAY = date(2022, 4, 1)
`

**Comment by heewonlee-nj** [comment]
다음 명령어로 secrets.txt 파일을 재생성할 수 있습니다.
```bash
docker-compose run --rm --entrypoint python app generate_secrets.py
```
